[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm>=7",
]
build-backend = "setuptools.build_meta"

[project]
name = "mnt-opdom-explorer"
description = "Explore Operational Domains of SiDB logic gates"
readme = "README.md"
authors = [
    { name = "Marcel Walter", email = "marcel.walter@tum.de" },
    { name = "Jan Drewniok", email = "jan.drewniok@tum.de" }
]
keywords = ["MNT", "field-coupled nanocomputing", "silicon dangling-bonds", "logic", "physical simulation", "design automation", "operational domain", "GUI"]
license = { file = "LICENSE.md" }
requires-python = ">=3.9"
version = "0.1.0"

dependencies = [
    "PyQt6==6.7.1",
    "matplotlib==3.9.0",
    "mnt.pyfiction==0.6.5",
    "pandas==2.2.2",
    "PyQt6==6.7.1",
    "qtawesome==1.3.1",
    "scikit-learn==1.5.2",
]

[project.optional-dependencies]
test = [
    "coverage>=6.0", # Ensure coverage is included for testing
]

[project.urls]
Repository = "https://github.com/cda-tum/mnt-opdom-explorer"
Homepage = "https://www.cda.cit.tum.de/research/nanotech/"
Issues = "https://github.com/cda-tum/mnt-opdom-explorer/issues"
Discussions = "https://github.com/cda-tum/mnt-opdom-explorer/discussions"

[tool.setuptools.packages.find]
include = ["core", "gui", "widgets"]
