[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm>=7",
]
build-backend = "setuptools.build_meta"

[project]
name = "opdom-explore"
description = "Explore Operational Domains of SiDB gates"
readme = "README.md"
authors = [
    { name = "Marcel Walter", email = "marcel.walter@tum.de" },
]
keywords = ["MNT", "field-coupled nanocomputing", "GUI"]
license = { file = "LICENSE" }
requires-python = ">=3.8"
version = "0.1.0"

dependencies = [
    "PyQt6>=6.0",
    "matplotlib==3.9.2",
    "mnt.pyfiction==0.6.3",
    "pandas==2.2.2",
    "PyQt6==6.7.1",
    "qtawesome==1.3.1"
]

[project.urls]
repository = "https://github.com/marcelwa/opdom-explore"

[tool.setuptools.packages.find]
include = ["core", "gui", "widgets"]