name: ☂️ • Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: macos-latest

    name: Coverage on Python 3.10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .[test]

      - name: Run Tests with Coverage
        run: |
          coverage run -m unittest discover --verbose
          coverage report
          coverage xml -o coverage.xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
